# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["/home/student/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]

  #create webserver
  config.vm.define "Test-Web01" do |web01_config|
  web01_config.vm.box = "ubuntu/bionic64"
  web01_config.vm.hostname = "Test-Web01"
  web01_config.vm.network :private_network, ip: "10.0.0.20"
  web01_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  web01_config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.gui = false
    vb.name = "Test-web01"
  end
 end
end
